## Numpy Assignments
### Array Creation and Manipulation

Q1. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10

In [2]:
import numpy as np

arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Q2. Write a NumPy program to create a 2D array with 1 on the border and 0 inside

In [5]:
arr = np.ones(shape=(3,3))
arr[1:-1 ,1:-1 ] = 0
print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


Q3. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [ ]:
arr = np.arange(2,11).reshape(3,3)
print("Before adding")
print(arr)

print("After adding")
arr[0,:] = 0
arr[-1,:] = 0
arr[:,0] = 0
arr[:,-1] = 0
print(arr)



Before adding
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
After adding
[[0 0 0]
 [0 6 0]
 [0 0 0]]


Q4.Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern

In [11]:
checker = np.zeros(shape=(8,8))
print(checker)
checker[::2 , 1::2] = 1
checker[1::2, ::2] = 1
print("\nChecker Board")
print(checker)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

Checker Board
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Q5. Write a NumPy program to create an array of ones and zeros.

In [15]:
print(np.eye(3,3, dtype =int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]


Q6.Write a NumPy program to change an array's dimension.

In [22]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


Q7.Write a NumPy program to create a contiguous flattened array.

In [19]:
arr = np.arange(2,11).reshape(3,3)
arr = arr.flatten()
print(arr)

[ 2  3  4  5  6  7  8  9 10]


Q8.Write a NumPy program to create another shape from an array without changing its data

In [26]:
arr = np.arange(2,14).reshape(3,4)
arr = arr.reshape(6,2)
print(arr)


[[ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]]


Q9.Write a NumPy program to create a new array of 3*5, filled with 2.

In [27]:
arr = np.ones(shape=(3,5))
arr = arr*2
print(arr)

[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


Q10.Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [29]:
arr = np.zeros((3,3,3),dtype=int)
i = range(3)

arr[i,i,i] = 1
print(arr)

[[[1 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 1 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 1]]]


Q11.Write a NumPy program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0's elsewhere.

In [34]:
arr= np.zeros((4,4),dtype=int)
i = range(4)
arr[i,i] = [4,5,6,8]
print(arr)

[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]


Q12.Write a NumPy program to collapse a 3-D array into a one-dimensional array.

In [37]:
arr = np.zeros((3,3,3),dtype=int)
i = range(3)

arr[i,i,i] = 1
print("Orginal arr: \n",arr,"\n")

arr = arr.flatten()
print(arr)

Orginal arr: 
 [[[1 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 1 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 1]]] 

[1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1]


Q13.Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.

In [4]:
arr = np.zeros(shape=(5,5), dtype=int)
i = range(5)
arr[:,:] = i
print(arr)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


Q14.Write a NumPy program to create a 5x5x5 cube of 1's.

In [6]:
print(np.ones((5,5,5),dtype= int))

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


### Indexing and Selection 

Q15.Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [3]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.arange(1,21).reshape(4,5)
r = np.isin(arr1,arr2)
print(r)

[ True  True  True  True  True  True  True]


Q16.Write a NumPy program to get the unique elements of an array.

In [6]:
arr = np.random.randint(1,21,size=(5,5))
print(arr)
print(np.unique_values(arr))

[[ 2 11  7  2 14]
 [ 2 13  2 15  5]
 [13 20  2 15 13]
 [14  4  7  4 17]
 [ 7 19 14 14 17]]
[ 2 11  7 14 13 15  5 20  4 17 19]


Q17.Write a NumPy program to find the set difference between two arrays. The set difference will return sorted, distinct values in array1 that are not in arra

In [3]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,7,18,8,45])
print(np.setdiff1d(arr1,arr2))

[2 3 4 5 6]


Q18.Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return sorted, distinct values in only one (not both) of the input arrays.

In [4]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,7,18,8,45])
print(np.setxor1d(arr1,arr2))

[ 2  3  4  5  6  8 18 45]


Q19.Write a NumPy program to find the union of two arrays. Union will return a unique, sorted array of values in each of the two input arrays

In [6]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,7,18,8,45])
print(np.union1d(arr1,arr2))

[ 1  2  3  4  5  6  7  8 18 45]


Q20.Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array

In [20]:
arr = np.random.randint(1,21,size=20)
a = arr[arr>10]
indices = np.where(arr>10)[0]
print([(int(i), int(v)) for i, v in zip(indices, a)])

[(0, 13), (1, 12), (2, 19), (4, 11), (5, 18), (6, 13), (13, 20), (14, 19), (15, 20), (16, 15), (17, 16), (19, 15)]


Q21.Write a NumPy program to get the number of non-zero elements in an array.

In [52]:
arr = np.random.randint(0,11,size=20)
a = arr[arr!= 0]
print(arr)
print(a)

[ 0  3  4  1  0  6  3  1  3 10 10 10  7  6  2  6  2  3  4  0]
[ 3  4  1  6  3  1  3 10 10 10  7  6  2  6  2  3  4]


Q22.Write a NumPy program to test whether specified values are present in an array.

In [3]:
arr = np.random.randint(1,21,size = 10)
print(arr,"\n")
r = np.isin(5,arr)
print(r)

[ 1 15 15 13 16 13 18 18 12  7] 

False


Q23.Write a NumPy program to replace the negative values in a NumPy array with 0.

In [ ]:
arr = np.random.randint(-21,21,size = 50)
print(arr,"\n")
arr[arr < 0 ] = 0
print(arr,"\n")

[-10 -19  -8  11  12   0  16   0  13 -13  -5   9  -9  -1  -9 -15  -6  19
 -18   9  -5 -18 -13  20  15  -4 -15  -3  12  -9  19   3   8 -18   9  -5
 -10 -17   8 -12  -7 -19 -15  20   7  -1   5 -18  11   0] 

[ 0  0  0 11 12  0 16  0 13  0  0  9  0  0  0  0  0 19  0  9  0  0  0 20
 15  0  0  0 12  0 19  3  8  0  9  0  0  0  8  0  0  0  0 20  7  0  5  0
 11  0] 



Q24.Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.

In [16]:
arr = np.random.randint(1,51,size = 20)
indices = np.where((arr > 30) | (arr<10))[0]
print(arr,"\n")

for i,j in zip(indices, arr[indices]):
    print(i,j)

[43 24 48  2 23 22 43 10 25 41  2 49 42 34 44 50 21 48 49 19] 

0 43
2 48
3 2
6 43
9 41
10 2
11 49
12 42
13 34
14 44
15 50
17 48
18 49
