# Numpy Assignments:
##### Broadcasting and Vectorized Operations

Q1. Write a NumPy program to compare two arrays using NumPy.

In [1]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6.7])
arr2 = np.array([1,2,3,4,5,6,8])
print(np.array_equiv(arr1,arr2))

False


Q2.Write a NumPy program (using numpy) to sum all the multiples of 3 or 5 below 100

In [2]:
arr = np.arange(1,101)
sum = np.sum(arr[(arr%3 == 0 ) | (arr%5 == 0)])
print(sum)

2418


Q3.Write a NumPy program to create an array of (3, 4) shapes, multiply every element value by 3 and display the result array.

In [3]:
arr = np.random.randint(1,21,size=(3,4))
print(arr,"\n")
arr =  arr*3
print(arr,"\n")

[[13  1 19 13]
 [ 6 19  2  6]
 [16  9 17 20]] 

[[39  3 57 39]
 [18 57  6 18]
 [48 27 51 60]] 



Q4.Write a NumPy program to replace all elements of NumPy array that are greater than the specified array.

In [12]:
arr1 = np.random.randint(1,11,size = (5,))
arr2 = np.random.randint(1,11,size = (5,))
print(arr1)
print(arr2)
arr1[arr1 < arr2] = arr2[arr1 < arr2]
print(arr1)

[9 2 3 1 3]
[5 4 7 4 6]
[9 4 7 4 6]


Q5.Write a NumPy program to replace the negative values in a NumPy array with 0.

In [20]:
arr1  = np.random.randint(-21,21,size =10)
print(arr1)
arr1[arr1<0] = 0 
print(arr1)

[-12   6  -4  20   2  12  12 -10 -14  -2]
[ 0  6  0 20  2 12 12  0  0  0]


Q6.Write a NumPy program to divide each row by a vector element.

In [21]:
arr1 = np.random.randint(1,21,size = (4,5))
arr2 = np.random.randint(1,21,size = (5, ))

print(arr1 / arr2)

[[1.5        1.25       1.33333333 0.64705882 5.        ]
 [1.2        0.375      0.33333333 0.47058824 4.33333333]
 [1.9        1.1875     0.13333333 0.05882353 1.        ]
 [1.6        0.125      0.86666667 0.17647059 4.        ]]


## Concatenation and Splitting

Q7.Write a NumPy program to concatenate two 2-dimensional arrays.

In [27]:
arr1 = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)
print(np.concatenate((arr1,arr2), axis=1))
print()
print(np.concatenate((arr1,arr2), axis=0))

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Q8.Write a NumPy program to convert 1-D arrays as columns into a 2-D array.

In [28]:
arr = np.array([1,2,3,4,4,5,5,6,7,7,8,8,9,9])
print(arr)
arr.reshape(2,7)

[1 2 3 4 4 5 5 6 7 7 8 8 9 9]


array([[1, 2, 3, 4, 4, 5, 5],
       [6, 7, 7, 8, 8, 9, 9]])

Q9.Write a NumPy program to convert (in sequence depth wise (along the third axis)) two 1-D arrays into a 2-D array.

In [38]:
arr1 = np.arange(1,11)
arr2 = np.arange(11,21)

print(np.dstack((arr1,arr2)))

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]
  [ 5 15]
  [ 6 16]
  [ 7 17]
  [ 8 18]
  [ 9 19]
  [10 20]]]


Q10.Write a NumPy program to split an array of 14 elements into 3 arrays, each with 2, 4, and 8 elements in the original order.

In [40]:
arr = np.arange(1,15)
r  = np.split(arr , [2,6])
for i in r:
    print(i)

[1 2]
[3 4 5 6]
[ 7  8  9 10 11 12 13 14]


Q11.Write  a NumPy program that splits an array of shape 4x4 into two arrays along the second axis.

In [4]:
arr = np.random.randint(1,21,size= (3,4))
arr1 , arr2 = np.split(arr,2, axis= 1 )
print(arr,"\n")
print(arr1,"\n")
print(arr2,"\n")


[[16  2 15 14]
 [20 12 10  9]
 [15  6  8 13]] 

[[16  2]
 [20 12]
 [15  6]] 

[[15 14]
 [10  9]
 [ 8 13]] 



## Mathematics and Linear Algebra

Q12.Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

In [25]:
arr = np.random.randint(1,51,size=(6,5))
print(arr,"\n")
max_idx = np.argmax(arr,axis=1) # Give row wise
min_idx = np.argmin(arr,axis=1) # Give row wise
print("Row wise:")
print(max_idx)
print(min_idx)
print("\nMax Values")
for i,idx in enumerate(max_idx):
    print(arr[i,idx],end=" ")
print("\nMin Values")
for i,idx in enumerate(min_idx):
    print(arr[i,idx],end=" ")
print()
max_idx = np.argmax(arr,axis=0) 
min_idx = np.argmin(arr,axis=0)
print("\nColumn Wise: ")
print(max_idx)
print(min_idx)
print("\nMax Values")
for i,idx in enumerate(max_idx):
    print(arr[idx,i],end=" ")

print("\nMin Values")
for i,idx in enumerate(min_idx):
    print(arr[idx,i],end=" ")



[[10 19 29  8 40]
 [22 18  2 39 33]
 [41 47  4  6 25]
 [38 43 20 10  3]
 [25 17 46 10 48]
 [ 9 29 49 42 20]] 

Row wise:
[4 3 1 1 4 2]
[3 2 2 4 3 0]

Max Values
40 39 47 43 48 49 
Min Values
8 2 4 3 10 9 

Column Wise: 
[2 2 5 5 4]
[5 4 1 2 3]

Max Values
41 47 49 42 48 
Min Values
9 17 2 6 3 

Q13.Write a NumPy program to get the magnitude of a vector in NumPy.

In [30]:
arr = np.array([3,4])
print(np.sqrt(np.sum(np.square(arr))))

5.0


Q14.Write a NumPy program to sum and compute the product of a numpy array of elements.

In [ ]:
arr = np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))

15
120


In [ ]:
arr = np.random.randint(1,21,size = (3,4))
print(np.sum(arr ,axis=0)) # Column wise sum 
print(np.prod(arr, axis=1)) # Row wise product

[18 34 48 51]
[ 4080 24276  8778]


Q15.Write a NumPy program to calculate the Euclidean distance.

In [6]:
arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([1,2,3,4,5,6,8])
euc = np.sqrt(np.sum(np.square(arr1 - arr2)))
print(euc)

1.0


## Practical Data Handling

Q16.Write a NumPy program to convert a NumPy array into a Python list structure.

In [8]:
arr = np.array([1,2,3,4])
arr.tolist()
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


Q17.Write a NumPy program to convert a NumPy array of floating values to a numpy array of integer values.

In [12]:
arr = np.array([1, 2, 4.4, 6.7])
arr1 = arr.astype(int)
print(arr)
print(arr1)

[1.  2.  4.4 6.7]
[1 2 4 6]


Q18.Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values

In [6]:
arr = np.array([[1,8,99],
                [4,5,np.nan],
                [9,10,np.inf],
                [7,18,45]])

arr = arr[np.isfinite(arr).all(axis=1)]
print(arr)

[[ 1.  8. 99.]
 [ 7. 18. 45.]]


Q19.Write a NumPy program to access the last two columns of a multidimensional column

In [9]:
arr = arr = np.array([[1,8,99],
                [4,5,6],
                [9,10,11],
                [7,18,45]])

print(arr[:,-2:])

[[ 8 99]
 [ 5  6]
 [10 11]
 [18 45]]
