# Module: NumPy Assignments
##  NumPy

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [3]:
import numpy as np
arr = np.random.randint(1,21,size = (5,5))
print("Array:")
print(arr)

arr[:,2] = 1
print("\nReplaced Array:")
print(arr)

Array:
[[20  1  5  3 15]
 [ 6 11  1  4  6]
 [13 11  3  9  9]
 [19 17 12 15 10]
 [15  6 20  8 18]]

Replaced Array:
[[20  1  1  3 15]
 [ 6 11  1  4  6]
 [13 11  1  9  9]
 [19 17  1 15 10]
 [15  6  1  8 18]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
import numpy as np 
arr = np.arange(1,17).reshape(4,4)
print("Array:")
print(arr)

np.fill_diagonal(arr , 0)
print("\nReplaced Array:")
print(arr)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Replaced Array:
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [4]:
import numpy as np 
arr = np.arange(1,37).reshape(6,6)
print("Array:")
print(arr)

print("\nSliced array:")
print(arr[2:5, 1:4])

Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sliced array:
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [8]:
arr = np.random.randint(1,21,size = (5,5))
print("Array:")
print(arr)

border = np.concatenate((arr[0 , :], arr[-1,:], arr[1:-1,0], arr[1:-1, -1]))
print("\nBorder array:")
print(border)

Array:
[[14 18 18 20  1]
 [13 16  6  8 10]
 [ 2 12  6 14 15]
 [ 1  8  5 14 12]
 [ 2 11 17 11 20]]

Border array:
[14 18 18 20  1  2 11 17 11 20 13  2  1 10 15 12]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [19]:
arr1 = np.random.randint(1,21,size = (3,4))
arr2 = np.random.randint(1,21,size = (3,4))

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

print("\nSum:")
print(arr1 + arr2)

print("\nDifference:")
print(arr1 - arr2)

print("\nProduct:")
print(arr1 * arr2)


print("\nDivision:")
print(arr1 / arr2)


Array 1:
[[ 8 14 10 14]
 [18 13 17 14]
 [ 9 15 16  9]]

Array 2:
[[19  8  5  2]
 [13  3  6  8]
 [ 6 19  7  8]]

Sum:
[[27 22 15 16]
 [31 16 23 22]
 [15 34 23 17]]

Difference:
[[-11   6   5  12]
 [  5  10  11   6]
 [  3  -4   9   1]]

Product:
[[152 112  50  28]
 [234  39 102 112]
 [ 54 285 112  72]]

Division:
[[0.42105263 1.75       2.         7.        ]
 [1.38461538 4.33333333 2.83333333 1.75      ]
 [1.5        0.78947368 2.28571429 1.125     ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [22]:
arr = np.arange(1,17).reshape(4,4)
row_sum = np.sum(arr, axis = 1)
col_sum = np.sum(arr, axis = 0)

print("Array:")
print(arr)

print("\nRow Sum:")
print(row_sum)

print("\nColumn Sum:")
print(col_sum)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Row Sum:
[10 26 42 58]

Column Sum:
[28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [23]:
arr = np.random.randint(1,21,size =(5,5))
mean = np.mean(arr)
median = np.median(arr)
sd = np.std(arr) 
var = np.var(arr)

print("Array")
print(arr)

print(f"\n Mean: {mean}")
print(f"Mediam: {median}")
print(f"Standard Deviation: {sd}")
print(f"Variance: {var}")



Array
[[ 6  7 14 15  8]
 [11 19  4 12 12]
 [19 14 13  7 10]
 [ 6 11  5  8 11]
 [ 9  5  7  8  2]]

 Mean: 9.72
Mediam: 9.0
Standard Deviation: 4.285043757069466
Variance: 18.3616


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [26]:
arr = np.arange(1,10).reshape(3,3)
mean = np.mean(arr)
sd = np.std(arr)

print("Array:")
print(arr)
Normalized_array = (arr - mean)/ sd

print("\nNormalized array:")
print(Normalized_array)


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Normalized array:
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [28]:
arr = np.random.randint(1,21,size= (3,3))

print("Array:")
print(arr)
d = np.array([7,18,45])
print("\n1D array:")
print(d)
result = arr + d
print("\nBroadcasting sum result:")
print(result)

Array:
[[ 3 16 19]
 [ 1  2  4]
 [ 8  8 14]]

1D array:
[ 7 18 45]

Broadcasting sum result:
[[10 34 64]
 [ 8 20 49]
 [15 26 59]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [ ]:
arr = np.random.randint(50,75,size = (4,4))

print("Array:")
print(arr)
d = np.array([7,18,45,8])
print("\n1D array:")
print(d)
result = arr - d
print("\nBroadcasting difference result:")
print(result)

Array:
[[73 67 50 50]
 [50 58 54 58]
 [57 57 74 63]
 [56 60 69 61]]

1D array:
[ 7 18 45  8]

Broadcasting difference result:
[[66 49  5 42]
 [43 40  9 50]
 [50 39 29 55]
 [49 42 24 53]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [ ]:
arr = np.random.randint(1,10,size=(3,3))
print("Matrix:")
print(arr)

d = np.linalg.det(arr)
print(f"\nDeterminant of matrix is: {d}")

i = np.linalg.inv(arr)
print(f"\nInverse matrix of matrix is:\n{i}")

eigen = np.linalg.eigvals(arr)
print(f"\nEigen Values of matrix are: {eigen}")


Array:
[[6 3 5]
 [1 4 7]
 [8 4 5]]

Determinant of matrix is: -34.99999999999999

Inverse matrix of matrix is:
[[ 0.22857143 -0.14285714 -0.02857143]
 [-1.45714286  0.28571429  1.05714286]
 [ 0.8         0.         -0.6       ]]

Eigen Values of matrix are: [14.63147223  1.74184436 -1.3733166 ]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [37]:
arr1 = np.random.randint(1,21,size = (2,3))
arr2 = np.random.randint(1,21,size = (3,2))

print("Matrix 1:")
print(arr1)

print("\nMatrix 2:")
print(arr2)

print(f"Matrix multiplication of matrices:\n{arr1 @ arr2}")

Matrix 1:
[[19  9  2]
 [ 6 12  2]]

Matrix 2:
[[ 1  3]
 [20 17]
 [ 1  9]]
Matrix multiplication of matrices:
[[201 228]
 [248 240]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [40]:
arr = np.arange(1,10).reshape(3,3)
print("Array:")
print(arr)
arr= arr.reshape(1,9)
print("\nNew Array 1:")
print(arr)
arr= arr.reshape(9,1)
print("\nNew Array 2:")
print(arr)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

New Array 1:
[[1 2 3 4 5 6 7 8 9]]

New Array 2:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [42]:
arr = np.arange(1,26).reshape(5,5)
print("Array:")
print(arr)
print()
arr = arr.reshape(25,)
print("Flatten Array:")
print(arr)
arr = arr.reshape(5,5)
print("Returned array")
print(arr)


Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Flatten Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
Returned array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [47]:
arr = np.random.randint(1,26,size=(5,5))
print("Array:")
print(arr)

corner = arr[[0,0,-1,-1],[0,-1,0,-1]]
print(f"\nCorner elements: {corner}")


Array:
[[19  4 13 21 11]
 [17 11  2  6 18]
 [15  6  8  4 11]
 [16  8 11  1  4]
 [24 22  5 10  5]]

Corner elements: [19 11 24  5]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [4]:
arr = arr = np.random.randint(1,21,size=(4,4))
print("Array:")
print(arr)

arr[arr>10] = 10
print("\nChanged Array:")
print(arr)

Array:
[[13  1 18  8]
 [17 14  7 17]
 [ 8 17  2 18]
 [ 4 14 15  1]]

Changed Array:
[[10  1 10  8]
 [10 10  7 10]
 [ 8 10  2 10]
 [ 4 10 10  1]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [14]:
datatype = [('name', 'U10'), ('age','i4'), ('weight', 'f4')]
arr = np.array([
    ('Lord Shiva',2,10000),
    ('Sathwik',18,74.5)
],dtype=datatype)
print("Array:")
print(arr)
np.sort(arr , order = 'age')
print("\nSorted array:")
print(arr,"\n")

print(f"{'Name':<15} {'Age':<5} {'Weight':<10}") # here < is for left allignment and > is for right allignment
for row in arr:
    print(f"{row['name']:<15} {row['age']:<5} {row['weight']:<10}")

Array:
[('Lord Shiva',  2, 10000. ) ('Sathwik', 18,    74.5)]

Sorted array:
[('Lord Shiva',  2, 10000. ) ('Sathwik', 18,    74.5)] 

Name            Age   Weight    
Lord Shiva      2     10000.0   
Sathwik         18    74.5      


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [20]:
datatype = [('x', 'i4'),('y', 'i4')]
arr = np.array([(1,2),(3,5),(7,18),(8,7)],dtype = datatype)
print(f"{'x':>5} {'y':>5}")
for row in arr:
    print(f"{row['x']:>5} {row['y']:>5}")

dist = np.sqrt((arr['x'][:, np.newaxis] - arr['x'])**2 + (arr['y'][:, np.newaxis] - arr['y'])**2)
print("Euclidean distances:")
print(dist)

    x     y
    1     2
    3     5
    7    18
    8     7
Euclidean distances:
[[ 0.          3.60555128 17.08800749  8.60232527]
 [ 3.60555128  0.         13.60147051  5.38516481]
 [17.08800749 13.60147051  0.         11.04536102]
 [ 8.60232527  5.38516481 11.04536102  0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [21]:
import numpy.ma  as ma 

arr = np.random.randint(1,21,size = (4,4))
masked = ma.masked_greater(arr , 10 )
print("Array:")
print(arr)

print("\nMasked Array:")
print(masked)

print("\nSum")
print(masked.sum())

Array:
[[ 1  8  8  9]
 [ 7 14  2  6]
 [11 20  2  7]
 [12  7 19 16]]

Masked Array:
[[1 8 8 9]
 [7 -- 2 6]
 [-- -- 2 7]
 [-- 7 -- --]]

Sum
57


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [30]:
import numpy.ma as ma

arr = np.random.randint(1,21,size=(3,3))
iden = np.eye(3 , dtype= bool)
masked = ma.masked_array(arr , mask= iden)
print("Array:")
print(arr)

print("\nMasked Array:")
print(masked)

mean = masked.mean()

masked = masked.filled(mean)
print("\nFilled Masked Array:")
print(masked)

Array:
[[11  6 17]
 [18 10 17]
 [11 13 16]]

Masked Array:
[[-- 6 17]
 [18 -- 17]
 [11 13 --]]

Filled Masked Array:
[[13  6 17]
 [18 13 17]
 [11 13 13]]
